### ISSUE TITLE
Practica 8

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-aras#1]
[Actividad 8 Planificación RoadMap y Kanban.pdf](https://github.com/user-attachments/files/17537692/Actividad.8.Planificacion.RoadMap.y.Kanban.pdf)

**Comment by Rufino07** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...solo deseo ver el repositorio...por favor.. @SANDRAVELASCO donde se implemento su proyecto

**Comment by SANDRAVELASCO** [comment]
https://github.com/SistemasTecTlaxiaco/SistemadeVentas Le dejo el link, @josealfredo79
