### ISSUE TITLE
Practica 10

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-aras#15]
[Practica 10 Contrato.pdf](https://github.com/user-attachments/files/18089597/Practica.10.Contrato.pdf)

**Comment by Luz1727** [comment]
calificacion 50%
Buen trabajo.

**Comment by josealfredo79** [comment]
bien hecho y revisado...
